package testutil

import (
	_ "embed"
	"encoding/hex"
	"encoding/json"
	"sync"
	"testing"
)

// jsVectors is generated by tools/jsvectors from @orbitdb/core 4.0.0.
//
//go:embed testdata/js-vectors.json
var jsVectors []byte

// Vectors is the decoded content of testdata/js-vectors.json.
type Vectors struct {
	Generator  string                    `json:"generator"`
	Identities map[string]IdentityVector `json:"identities"`
	Entries    []EntryVector             `json:"entries"`
	Logs       map[string]LogScenario    `json:"logs"`
	Iterators  IteratorVectors           `json:"iterators"`
	Manifests  []ManifestVector          `json:"manifests"`
	Addresses  []AddressVector           `json:"addresses"`
	Encryption map[string]EncryptionCase `json:"encryption"`
	// SimpleEncryption are ciphertexts of @orbitdb/simple-encryption.
	SimpleEncryption []struct {
		Password   string `json:"password"`
		Plaintext  Hex    `json:"plaintext"`
		Ciphertext Hex    `json:"ciphertext"`
	} `json:"simpleEncryption"`
}

// IdentityVector is an identity created for a fixture key id.
type IdentityVector struct {
	ID         string            `json:"id"`
	PublicKey  string            `json:"publicKey"`
	Signatures map[string]string `json:"signatures"`
	Type       string            `json:"type"`
	Hash       string            `json:"hash"`
	Bytes      Hex               `json:"bytes"`
}

// EntryVector is a single entry created by userA (or Writer).
type EntryVector struct {
	Name      string   `json:"name"`
	LogID     string   `json:"logId"`
	Writer    string   `json:"writer"`
	ClockTime int64    `json:"clockTime"`
	Next      []string `json:"next"`
	Refs      []string `json:"refs"`
	Payload   any      `json:"payload"`
	Hash      string   `json:"hash"`
	Bytes     Hex      `json:"bytes"`
}

// LogScenario is a sequence of log operations and the resulting logs.
//
// Ops are ["append", log, payload, referencesCount], ["join", into, from]
// or ["joinEntry", into, from, index].
type LogScenario struct {
	LogID   string               `json:"logId"`
	Writers map[string]string    `json:"writers"`
	Ops     [][]any              `json:"ops"`
	Results []any                `json:"results"`
	Final   map[string]LogResult `json:"final"`
}

// LogResult describes a log at the end of a scenario.
type LogResult struct {
	Values []ValueVector `json:"values"`
	Heads  []string      `json:"heads"`
	Clock  ClockVector   `json:"clock"`
}

// ValueVector is one entry of LogResult.Values.
type ValueVector struct {
	Hash    string      `json:"hash"`
	Payload any         `json:"payload"`
	Next    []string    `json:"next"`
	Refs    []string    `json:"refs"`
	Clock   ClockVector `json:"clock"`
}

// ClockVector is a Lamport clock.
type ClockVector struct {
	ID   string `json:"id"`
	Time int64  `json:"time"`
}

// IteratorVectors are Log.Iterator results over a 100-entry log.
type IteratorVectors struct {
	LogID  string         `json:"logId"`
	Writer string         `json:"writer"`
	Size   int            `json:"size"`
	Hashes []string       `json:"hashes"`
	Cases  []IteratorCase `json:"cases"`
}

// IteratorCase gives iterator options as indexes into IteratorVectors.Hashes.
type IteratorCase struct {
	Options struct {
		GT     *int `json:"gt"`
		GTE    *int `json:"gte"`
		LT     *int `json:"lt"`
		LTE    *int `json:"lte"`
		Amount *int `json:"amount"`
	} `json:"options"`
	Payloads []string `json:"payloads"`
}

// ManifestVector is a database manifest with its access controller.
type ManifestVector struct {
	Write                 []string       `json:"write"`
	AccessController      string         `json:"accessController"`
	AccessControllerBytes Hex            `json:"accessControllerBytes"`
	Name                  string         `json:"name"`
	Type                  string         `json:"type"`
	Meta                  any            `json:"meta"`
	Hash                  string         `json:"hash"`
	Bytes                 Hex            `json:"bytes"`
	Manifest              map[string]any `json:"manifest"`
	Address               string         `json:"address"`
	HeadsProtocol         string         `json:"headsProtocol"`
}

// AddressVector is the result of isValidAddress and OrbitDBAddress.
type AddressVector struct {
	Address string  `json:"address"`
	Valid   bool    `json:"valid"`
	String  *string `json:"string"`
}

// EncryptionCase is a log written with the toy cipher of the generator.
type EncryptionCase struct {
	LogID    string `json:"logId"`
	Writer   string `json:"writer"`
	Appended []struct {
		Hash  string `json:"hash"`
		Bytes Hex    `json:"bytes"`
	} `json:"appended"`
	Payloads []any `json:"payloads"`
}

// Hex is a byte slice that unmarshals from a hex string.
type Hex []byte

// UnmarshalJSON implements json.Unmarshaler.
func (h *Hex) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}
	d, err := hex.DecodeString(s)
	*h = d
	return err
}

var (
	vectorsOnce sync.Once
	vectors     Vectors
	vectorsErr  error
)

// JSVectors returns the golden vectors.
func JSVectors(t testing.TB) *Vectors {
	t.Helper()
	vectorsOnce.Do(func() { vectorsErr = json.Unmarshal(jsVectors, &vectors) })
	if vectorsErr != nil {
		t.Fatal(vectorsErr)
	}
	return &vectors
}
